service: sharies-nestjs-graphql-serverless

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  profile: default # Config your AWS Profile
  environment: # Service wide environment variables
    NODE_ENV: production

plugins:
  - serverless-offline

#package:
#  exclude:
#    - .git/**
#    - src/**
#    - test/**
#    - nodemon.json
#    - README.md
#  excludeDevDependencies: true

functions:
  index:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
